apiVersion: v1
kind: Service
metadata: 
  name: hi-svc
spec:
  selector:
    finder: hi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata: 
  name: hel-svc
spec:
  selector:
    finder: hel
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8081
